trailingComma: "all"
semi: false
singleQuote: true
bracketSpacing: true
endOfLine: "auto"
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    options:
      semi: true
      parser: "typescript"
